// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irjmmwhcnvhuweuxsmzl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlyam1td2hjbnZodXdldXhzbXpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNTIxNTgsImV4cCI6MjA3NDcyODE1OH0.fTmIWxho2L24wY8U1Dw-egeEyyjPAbQpMc5wZrZ09wk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});